const finite=Number.isFinite;
const mean=a=>{const x=a.filter(finite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:NaN};
const median=a=>{const x=a.filter(finite).sort((a,b)=>a-b);if(!x.length)return NaN;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
function interp(series,t,key){let best=null,d=Infinity;for(const r of series){if(!finite(r[key]))continue;const q=Math.abs(r.t-t);if(q<d){d=q;best=r}}return best?.[key]}
function resample(series,start,end,step=5){const out=[];for(let t=start;t<=end;t+=step){const speed=interp(series,t,'speedMph'),hr=interp(series,t,'hr');if(finite(speed)&&speed>1&&finite(hr)&&hr>40)out.push({t,speed,hr,ef:speed/hr})}return out}
function windowMean(x,a,b,key){return mean(x.filter(r=>r.t>=a&&r.t<=b).map(r=>r[key]))}
function linfit(x,key='ef'){if(x.length<3)return null;const mx=mean(x.map(r=>r.t)),my=mean(x.map(r=>r[key]));const den=x.reduce((s,r)=>s+(r.t-mx)**2,0);if(!den)return null;const slope=x.reduce((s,r)=>s+(r.t-mx)*(r[key]-my),0)/den,intercept=my-slope*mx;const sse=x.reduce((s,r)=>s+(r[key]-(intercept+slope*r.t))**2,0);return {slope,intercept,sse}}
function confidence(n,quality=true){return !quality||n<40?'Low':n<100?'Moderate':'High'}
function movingMean(a,key,radius=2){return a.map((row,i)=>{const z=a.slice(Math.max(0,i-radius),Math.min(a.length,i+radius+1)).map(q=>q[key]).filter(finite);return z.length?mean(z):NaN})}
function corrLag(a,b,maxLag=24){let best=null;for(let k=0;k<=maxLag;k++){const aa=[],bb=[];for(let i=0;i<a.length-k;i++){if(finite(a[i])&&finite(b[i+k])){aa.push(a[i]);bb.push(b[i+k])}}const r=corr(aa,bb);if(finite(r)&&(!best||r>best.r))best={k,r}}return best}
export function experimentalMetrics(analysis){
 const raw=analysis?.series||[]; if(raw.length<30)return {available:false,reason:'Not enough usable time-series data.'};
 const start=analysis.analysisStartS??analysis.startS??raw[0].t,end=analysis.analysisEndS??analysis.endS??raw.at(-1).t,dur=end-start;
 const x=resample(raw,start,end,5); if(x.length<30||dur<600)return {available:false,reason:'Experimental metrics need at least 10 minutes of usable speed and heart-rate data.'};
 const q1=start+.20*dur,q2=start+.40*dur,q3=start+.60*dur,q4=start+.80*dur;
 const early=windowMean(x,q1,q2,'ef'),late=windowMean(x,q3,q4,'ef');
 const di=finite(early)&&early>0&&finite(late)?100*late/early:NaN;
 const durability={value:di,loss:finite(di)?100-di:NaN,early,late,confidence:confidence(x.length,dur>=1200)};
 // Piecewise breakpoint: smooth efficiency first, search central 20–80%, and require a meaningful late deterioration.
 const efSmooth=movingMean(x,'ef',3), xf=x.map((r,i)=>({...r,ef:efSmooth[i]})).filter(r=>finite(r.ef));
 let best=null; const base=linfit(xf); for(let f=.20;f<=.80;f+=.025){const t=start+f*dur,a=xf.filter(r=>r.t<=t),b=xf.filter(r=>r.t>t);if(a.length<18||b.length<18)continue;const fa=linfit(a),fb=linfit(b);if(!fa||!fb)continue;const sse=fa.sse+fb.sse;if(!best||sse<best.sse)best={t,f,sse,pre:fa.slope,post:fb.slope}}
 let fip=null;if(best&&base&&base.sse>0){const improve=1-best.sse/base.sse,efMean=mean(xf.map(r=>r.ef))||1,postPctHr=best.post/efMean*3600*100,prePctHr=best.pre/efMean*3600*100;const deterioration=postPctHr-prePctHr;if(improve>.025&&postPctHr<-.25&&deterioration<-.25)fip={timeS:best.t-start,pct:best.f*100,declinePctHr:postPctHr,improvement:improve,method:'segmented',confidence:confidence(xf.length,improve>.07&&postPctHr<-.8)}}
 // Many real runs lose efficiency gradually rather than developing a sharper negative slope. If segmented regression
 // does not find that shape, detect the first sustained departure from the runner's own early-run efficiency baseline.
 if(!fip&&finite(early)&&early>0){const search=xf.filter(r=>r.t>=q2&&r.t<=start+.90*dur),threshold=early*.98,need=dur>=3600?6:5;let hit=null;for(let i=0;i<=search.length-need;i++){const block=search.slice(i,i+need);if(block.every(r=>r.ef<=threshold)){const after=xf.filter(r=>r.t>=block[0].t),afterMean=mean(after.map(r=>r.ef));if(finite(afterMean)&&afterMean<=early*.985){hit=block[0];break}}}if(hit){const after=xf.filter(r=>r.t>=hit.t),fit=linfit(after),efMean=mean(xf.map(r=>r.ef))||1,postPctHr=fit?fit.slope/efMean*3600*100:NaN;fip={timeS:hit.t-start,pct:(hit.t-start)/dur*100,declinePctHr:postPctHr,improvement:NaN,method:'sustained-loss',confidence:confidence(xf.length,(hit.t-start)>=.4*dur&&after.length>=24)}}}
 // Hysteresis: normalized shoelace area of speed-HR trajectory.
 const sp=x.map(r=>r.speed),hr=x.map(r=>r.hr),sp5=percentile(sp,.05),sp95=percentile(sp,.95),h5=percentile(hr,.05),h95=percentile(hr,.95);let area=0;for(let i=1;i<x.length;i++)area+=(x[i-1].speed*x[i].hr-x[i].speed*x[i-1].hr)/2;if(x.length>2)area+=(x.at(-1).speed*x[0].hr-x[0].speed*x.at(-1).hr)/2;const denom=(sp95-sp5)*(h95-h5);const variation=sp95-sp5;const phh=denom>0&&variation>=.5?Math.abs(area)/denom:NaN;
 const hysteresis={value:phh,variationMph:variation,confidence:finite(phh)?confidence(x.length,variation>=.8):'Unavailable'};
 // Response lag: smooth both signals, then correlate their short-window changes over 0..120 s.
 const smSpeed=movingMean(x,'speed',2),smHr=movingMean(x,'hr',2),deltaN=3,ds=[],dh=[];for(let i=deltaN;i<x.length;i++){ds.push(smSpeed[i]-smSpeed[i-deltaN]);dh.push(smHr[i]-smHr[i-deltaN])}const lagBest=corrLag(ds,dh,24);
 const arl=lagBest&&lagBest.r>=.10&&variation>=.35?{seconds:lagBest.k*5,correlation:lagBest.r,confidence:confidence(x.length,lagBest.r>=.22&&variation>=.6)}:null;
 // Recovery kinetics: find separated HR peaks followed by sustained decline over the next 60–120 s.
 const rec=[],hrSmooth=movingMean(x,'hr',2),speedSmooth=movingMean(x,'speed',2);let lastPeak=-999;for(let i=6;i<x.length-14;i++){if(i-lastPeak<12)continue;const before=hrSmooth.slice(Math.max(0,i-5),i+1),after=hrSmooth.slice(i+1,Math.min(x.length,i+25));if(after.length<12)continue;const peak=Math.max(...before),peakOffset=before.lastIndexOf(peak),peakIdx=Math.max(0,i-5)+peakOffset,preSpeed=mean(speedSmooth.slice(Math.max(0,i-5),i+1)),postSpeed=mean(speedSmooth.slice(i+1,Math.min(x.length,i+7))),workloadDrop=finite(preSpeed)&&finite(postSpeed)?preSpeed-postSpeed:0,futureMin=Math.min(...after),drop=peak-futureMin;if(drop<5||workloadDrop<.20)continue;const h60=interp(x,x[peakIdx].t+60,'hr'),hrr60=finite(h60)?peak-h60:NaN;if(!finite(hrr60)||hrr60<3)continue;const floor=median(after.slice(Math.max(0,after.length-8)));if(!finite(floor)||peak-floor<4)continue;const ys=[];const endi=Math.min(x.length-1,peakIdx+24);for(let j=peakIdx+1;j<=endi;j++){const hv=hrSmooth[j],ratio=(hv-floor)/(peak-floor);if(ratio>.03&&ratio<.98)ys.push({t:x[j].t-x[peakIdx].t,ef:Math.log(ratio)})}const fit=linfit(ys),tau=fit&&fit.slope<0?-1/fit.slope:NaN;if(finite(tau)&&tau>=5&&tau<=360&&ys.length>=5){const curve=x.slice(peakIdx,endi+1).map((r,k)=>({t:r.t-x[peakIdx].t,hr:hrSmooth[peakIdx+k],relative:hrSmooth[peakIdx+k]-peak}));rec.push({t:x[peakIdx].t-start,hrr60,tau,peakHr:peak,floor,workloadDrop,curve});lastPeak=peakIdx}}
 const recovery=rec.length?{count:rec.length,hrr60:median(rec.map(r=>r.hrr60)),tau:median(rec.map(r=>r.tau)),events:rec,confidence:rec.length>=3?'High':rec.length===2?'Moderate':'Low'}:null;
 return {available:true,durationS:dur,samples:x.length,series:x,durability,fip,hysteresis,arl,recovery};
}
function percentile(a,p){const x=a.filter(finite).sort((a,b)=>a-b);if(!x.length)return NaN;const z=(x.length-1)*p,l=Math.floor(z),h=Math.ceil(z);return l===h?x[l]:x[l]+(x[h]-x[l])*(z-l)}
function corr(a,b){if(a.length<8||a.length!==b.length)return NaN;const ma=mean(a),mb=mean(b),da=Math.sqrt(a.reduce((s,v)=>s+(v-ma)**2,0)),db=Math.sqrt(b.reduce((s,v)=>s+(v-mb)**2,0));return da&&db?a.reduce((s,v,i)=>s+(v-ma)*(b[i]-mb),0)/(da*db):NaN}
