const RECORD=20, LAP=19, SESSION=18, ACTIVITY=34;
const finite=Number.isFinite;

function readUInt(buf,pos,size,little){ if(![1,2,4,8].includes(size))return null; let invalid=true; for(let i=0;i<size;i++) if(buf[pos+i]!==255){invalid=false;break;} if(invalid)return null; const dv=new DataView(buf.buffer,buf.byteOffset+pos,size); if(size===1)return dv.getUint8(0); if(size===2)return dv.getUint16(0,little); if(size===4)return dv.getUint32(0,little); if(size===8){const v=dv.getBigUint64(0,little); return Number(v);} }
function writeUInt(buf,pos,size,little,value){ if(![1,2,4,8].includes(size))return; const max=Math.pow(2,8*size)-2; const iv=Math.max(0,Math.min(max,Math.round(value))); const dv=new DataView(buf.buffer,buf.byteOffset+pos,size); if(size===1)dv.setUint8(0,iv); else if(size===2)dv.setUint16(0,iv,little); else if(size===4)dv.setUint32(0,iv,little); else dv.setBigUint64(0,BigInt(iv),little); }
function crc(data,seed=0){let c=seed; for(const byte of data){c^=byte; for(let i=0;i<8;i++) c=(c&1)?((c>>>1)^0xA001):(c>>>1);} return c&0xffff;}
function layout(defn,compressed){let offset=0,out=[]; defn.fields.forEach((f,i)=>{if(compressed&&i===0&&f.num===253)return; out.push([f,offset]); offset+=f.size;}); return out;}
function parseCore(input){const raw=new Uint8Array(input); if(raw.length<14)throw new Error('The selected file is too small to be a FIT file.'); const headerSize=raw[0]; if(headerSize<12)throw new Error('Unsupported FIT header.'); if(String.fromCharCode(...raw.slice(8,12))!=='.FIT')throw new Error('The selected file does not contain a FIT header.'); const dv=new DataView(raw.buffer,raw.byteOffset,raw.byteLength); const dataSize=dv.getUint32(4,true), dataStart=headerSize, dataEnd=dataStart+dataSize; if(dataEnd>raw.length-2)throw new Error('The FIT file appears truncated.'); const definitions=new Map(), messages=[]; let pos=dataStart;
 while(pos<dataEnd){const hpos=pos, header=raw[pos++]; if(header&0x80){const local=(header>>5)&3, defn=definitions.get(local); if(!defn)throw new Error(`FIT compressed data references undefined local message ${local}.`); const lay=layout(defn,true); const payloadSize=lay.reduce((s,[f])=>s+f.size,0)+defn.dev.reduce((a,b)=>a+b,0); messages.push({hpos,defn,lay,payload:pos}); pos+=payloadSize; continue;} const local=header&15; if(header&0x40){ if(pos+5>dataEnd)throw new Error('Truncated FIT definition message.'); pos++; const architecture=raw[pos++], little=architecture===0; const gdv=new DataView(raw.buffer,raw.byteOffset+pos,2); const globalNum=gdv.getUint16(0,little); pos+=2; const nfields=raw[pos++], fields=[]; for(let i=0;i<nfields;i++){if(pos+3>dataEnd)throw new Error('Truncated FIT field definition.'); fields.push({num:raw[pos],size:raw[pos+1],base:raw[pos+2]}); pos+=3;} const dev=[]; if(header&0x20){const ndev=raw[pos++]; for(let i=0;i<ndev;i++){if(pos+3>dataEnd)throw new Error('Truncated FIT developer field definition.'); dev.push(raw[pos+1]); pos+=3;}} definitions.set(local,{globalNum,little,fields,dev}); continue;} const defn=definitions.get(local); if(!defn)throw new Error(`FIT data references undefined local message ${local}.`); const lay=layout(defn,false), payloadSize=lay.reduce((s,[f])=>s+f.size,0)+defn.dev.reduce((a,b)=>a+b,0); messages.push({hpos,defn,lay,payload:pos}); pos+=payloadSize; }
 return {raw,headerSize,dataEnd,messages}; }
function field(raw,msg,num,scale=1){for(const [f,off] of msg.lay){if(f.num===num){const v=readUInt(raw,msg.payload+off,f.size,msg.defn.little); return v==null?NaN:v/scale;}} return NaN;}
export function inspectFit(input){const core=parseCore(input), {raw,messages}=core; const sessions=[],laps=[],records=[]; let lastDistance=NaN,avgHr=NaN,maxHr=NaN; for(const m of messages){if(m.defn.globalNum===SESSION){sessions.push({distanceM:field(raw,m,9,100),elapsedS:field(raw,m,7,1000),timerS:field(raw,m,8,1000),avgSpeed:field(raw,m,14,1000)}); const ah=field(raw,m,16),mh=field(raw,m,17); if(finite(ah))avgHr=ah;if(finite(mh))maxHr=mh;} else if(m.defn.globalNum===LAP){laps.push({distanceM:field(raw,m,9,100),elapsedS:field(raw,m,7,1000),timerS:field(raw,m,8,1000),avgHr:field(raw,m,15),maxHr:field(raw,m,16),cadence:field(raw,m,17)});} else if(m.defn.globalNum===RECORD){const d=field(raw,m,5,100); if(finite(d))lastDistance=d; records.push({timestamp:field(raw,m,253),hr:field(raw,m,3),cadence:field(raw,m,4),distanceM:d,speedMps:finite(field(raw,m,73,1000))?field(raw,m,73,1000):field(raw,m,6,1000)});}}
 if(!sessions.length)throw new Error('No FIT Session message was found. Endurance Forge only supports Activity FIT files here.'); const s=sessions.at(-1), originalDistanceM=finite(s.distanceM)?s.distanceM:lastDistance, originalTimerS=finite(s.timerS)?s.timerS:s.elapsedS; if(!finite(originalDistanceM)||originalDistanceM<=0)throw new Error('The FIT file does not contain a usable session distance.'); if(!finite(originalTimerS)||originalTimerS<=0)throw new Error('The FIT file does not contain a usable session timer time.'); return {originalDistanceM,originalTimerS,originalElapsedS:finite(s.elapsedS)?s.elapsedS:originalTimerS,avgHr,maxHr,laps,lapCount:laps.length,records}; }
export function correctFit(input,targetDistanceM,targetTimerS){if(!(targetDistanceM>0))throw new Error('Corrected treadmill distance must be greater than zero.'); if(!(targetTimerS>0))throw new Error('Corrected treadmill time must be greater than zero.'); const info=inspectFit(input), core=parseCore(new Uint8Array(input).slice()), raw=core.raw; const distFactor=targetDistanceM/info.originalDistanceM,timeFactor=targetTimerS/info.originalTimerS,speedFactor=distFactor/timeFactor; const rules=new Map([[RECORD,new Map([[5,distFactor],[6,speedFactor],[73,speedFactor]])],[LAP,new Map([[7,timeFactor],[8,timeFactor],[9,distFactor],[13,speedFactor],[14,speedFactor],[110,speedFactor],[111,speedFactor]])],[SESSION,new Map([[7,timeFactor],[8,timeFactor],[9,distFactor],[14,speedFactor],[15,speedFactor],[59,timeFactor],[69,timeFactor],[78,timeFactor],[124,speedFactor],[125,speedFactor]])],[ACTIVITY,new Map([[0,timeFactor]])]]); let changed=0; for(const m of core.messages){const rr=rules.get(m.defn.globalNum); if(!rr)continue; for(const [f,off] of m.lay){const factor=rr.get(f.num); if(factor==null)continue; const v=readUInt(raw,m.payload+off,f.size,m.defn.little); if(v==null)continue; writeUInt(raw,m.payload+off,f.size,m.defn.little,v*factor);changed++;}}
 if(core.headerSize>=14){const h=crc(raw.slice(0,12)); raw[12]=h&255;raw[13]=(h>>8)&255;} const c=crc(raw.slice(0,core.dataEnd)); raw[core.dataEnd]=c&255; raw[core.dataEnd+1]=(c>>8)&255; return {bytes:raw.slice(0,core.dataEnd+2),distFactor,timeFactor,speedFactor,changed}; }
export function formatDuration(sec){sec=Math.round(sec||0); const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60; return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;}
export function pacePerMile(miles,seconds){if(!(miles>0&&seconds>0))return '—'; const p=seconds/miles, m=Math.floor(p/60),s=Math.round(p%60); return `${m}:${String(s===60?0:s).padStart(2,'0')}${s===60?'*':''}`;}
export function oxygenCostLevelRun(mph,gradePct=0){const mMin=mph*26.8224, grade=gradePct/100; return 0.2*mMin+0.9*mMin*grade+3.5;}
export function hrDrift(records){const hr=records.map(r=>r.hr).filter(x=>finite(x)&&x>=70&&x<=230); if(hr.length<40)return null; const cut=Math.floor(hr.length/2), a=hr.slice(0,cut).reduce((x,y)=>x+y,0)/cut,b=hr.slice(cut).reduce((x,y)=>x+y,0)/(hr.length-cut); return (b/a-1)*100;}
