import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { formatDuration, pacePerMile, oxygenCostLevelRun } from './fit.js';
import { importActivity, correctActivityFile, capabilityRows } from './activity.js';
import { analyzeTreadmillActivity } from './analysis.js';
import { combineAerobicFitness } from './multirun.js';

const MILES_PER_METER=1/1609.344, supported=['FIT','TCX','GPX'];
function Logo(){return <div className="brand"><div className="mark">EF</div><div><strong>ENDURANCE FORGE</strong><span>RUNNING PERFORMANCE ANALYTICS</span></div></div>}
const pagePaths={home:'/',analyze:'/analyze/',compare:'/compare/',guide:'/metrics/',method:'/methodology/'};
const pathPages={'/':'home','/analyze':'analyze','/analyze/':'analyze','/compare':'compare','/compare/':'compare','/metrics':'guide','/metrics/':'guide','/methodology':'method','/methodology/':'method'};
const pageMeta={
 home:{title:'Endurance Forge | Treadmill Running Analytics',description:'Analyze treadmill FIT, TCX, and GPX activities locally in your browser. Explore heart-rate drift, workload oxygen cost, and a treadmill-derived VO₂max-equivalent aerobic fitness estimate.'},
 analyze:{title:'Treadmill Run Analyzer | Endurance Forge',description:'Analyze a treadmill activity using treadmill distance, time, grade, heart rate, workout segmentation, HR drift, and an aerobic fitness estimate.'},
 compare:{title:'Compare Treadmill Runs | Endurance Forge',description:'Compare treadmill runs and combine qualifying workload and heart-rate observations into a robust multi-run EF Aerobic Fitness Estimate.'},
 guide:{title:'Running Metrics Guide | Endurance Forge',description:'Learn how Endurance Forge interprets aerobic fitness estimates, running oxygen cost, HR drift, heart-rate reserve, stable analysis windows, and data quality.'},
 method:{title:'Analysis Methodology | Endurance Forge',description:'Read the Endurance Forge methodology for single-run and robust multi-run aerobic fitness inference, workload oxygen cost, heart-rate reserve, and drift.'}
};
function pageFromLocation(){return pathPages[window.location.pathname]||'home'}
function Shell({children,page,go}){return <div className="app"><header><Logo/><nav><button className={page==='home'?'active':''} onClick={()=>go('home')}>Home</button><button className={page==='analyze'?'active':''} onClick={()=>go('analyze')}>Analyze</button><button className={page==='compare'?'active':''} onClick={()=>go('compare')}>Compare Runs</button><button className={page==='guide'?'active':''} onClick={()=>go('guide')}>Metrics Guide</button><button className={page==='method'?'active':''} onClick={()=>go('method')}>Methodology</button></nav><div className="privacy">PUBLIC BETA · LOCAL-FIRST</div></header><main>{children}</main><footer><Logo/><div className="footer-center"><p>Endurance Forge is a public beta. Metrics are analytical estimates, not device-manufacturer metrics or laboratory measurements.</p><a className="coffee-button footer-coffee" href="https://buymeacoffee.com/enduranceforge" target="_blank" rel="noreferrer">☕ Buy the developer a coffee</a></div><span>FIT · TCX · GPX processed locally</span></footer></div>}
function FormatChips(){return <div className="format-chips">{supported.map(x=><span key={x}>{x}</span>)}</div>}
function Home({go}){return <><section className="hero"><div className="eyebrow">TREADMILL DATA, FORGED INTO INSIGHT</div><h1>Your treadmill run is more than a device summary.</h1><p>Analyze FIT, TCX, and GPX treadmill activities, isolate meaningful running segments, quantify aerobic workload and heart-rate drift, and generate a treadmill-derived VO₂max-equivalent aerobic fitness estimate when the data supports it — without uploading raw activity files.</p><FormatChips/><div className="hero-actions"><button className="primary" onClick={()=>go('analyze')}>Analyze a treadmill run</button><button className="secondary" onClick={()=>go('compare')}>Compare several runs</button></div><div className="trust"><span>✓ Browser-local processing</span><span>✓ Segment-aware analysis</span><span>✓ VO₂max-equivalent estimate clearly labeled</span><span>✓ Public beta · methodology published</span></div></section><section className="feature-grid"><article><div className="icon">01</div><h3>Import the activity</h3><p>FIT, TCX, and GPX are normalized into one Endurance Forge activity model so analysis is not tied to one device maker.</p></article><article><div className="icon">02</div><h3>Detect the workout structure</h3><p>Sustained running is separated from walking, warm-up, recovery, and cooldown so unlike workloads are not blindly compared.</p></article><article><div className="icon">03</div><h3>Analyze the right segment</h3><p>Heart-rate drift and EF aerobic fitness estimates use the selected running segment and clearly report confidence and limitations.</p></article></section><section className="banner"><div><div className="eyebrow">TREADMILL PERFORMANCE ANALYTICS</div><h2>Analyze the comparable portion of your workout without blending warm-up, walking, and sustained running into a single physiological result.</h2></div><button className="secondary" onClick={()=>go('method')}>See the methodology</button></section></>}
function DropZone({onFiles,multiple=false,title='Drop an activity file here'}){const[drag,setDrag]=useState(false);return <label className={'drop '+(drag?'drag':'')} onDragEnter={()=>setDrag(true)} onDragLeave={()=>setDrag(false)} onDrop={()=>setDrag(false)}><input type="file" accept=".fit,.tcx,.gpx" multiple={multiple} onChange={e=>onFiles([...e.target.files])}/><div className="upload-icon">⇧</div><strong>{title}</strong><span>or click to browse · FIT, TCX, GPX</span><FormatChips/><small>Processed locally in this browser</small></label>}
function Metric({label,value,sub,tone=''}){return <div className={'metric '+tone}><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Capabilities({activity}){return <div className="cap-grid">{capabilityRows(activity).map(([n,ok])=><div className={'cap '+(ok?'yes':'no')} key={n}><b>{ok?'✓':'—'}</b><span>{n}</span></div>)}</div>}
function safeMiles(a){return a?.capabilities.distance?a.recordedDistanceM*MILES_PER_METER:NaN}
function safeTime(a){return a?.capabilities.duration?a.recordedTimerS:NaN}
function parseClock(v){if(!v)return NaN;const p=v.trim().split(':').map(Number);if(p.some(Number.isNaN))return NaN;if(p.length===3)return p[0]*3600+p[1]*60+p[2];if(p.length===2)return p[0]*60+p[1];const n=Number(v);return Number.isFinite(n)?n:NaN}
function fmtMph(v){return Number.isFinite(v)?v.toFixed(2)+' mph':'—'}
function confidenceClass(c){return c==='High'?'good':c==='Moderate'?'moderate':c==='Low'?'low':''}

function ActivityChart({analysis}){
 if(!analysis?.series?.length)return null;
 const data=analysis.series.filter(r=>Number.isFinite(r.t)&&(Number.isFinite(r.hr)||Number.isFinite(r.speedMph)));
 if(data.length<5)return null;
 const W=1000,H=230,pad=34,maxT=Math.max(...data.map(r=>r.t),1),hrs=data.map(r=>r.hr).filter(Number.isFinite),sps=data.map(r=>r.speedMph).filter(Number.isFinite);
 const minHr=Math.min(...hrs,60),maxHr=Math.max(...hrs,180),maxSp=Math.max(...sps,6);
 const x=t=>pad+(t/maxT)*(W-pad*2), yHr=v=>H-pad-((v-minHr)/Math.max(1,maxHr-minHr))*(H-pad*2), ySp=v=>H-pad-(v/Math.max(1,maxSp))*(H-pad*2);
 const path=(key,y)=>data.filter(r=>Number.isFinite(r[key])).map((r,i)=>(i?'L':'M')+x(r.t).toFixed(1)+' '+y(r[key]).toFixed(1)).join(' ');
 const sx=x(analysis.analysisStartS),ex=x(analysis.analysisEndS);
 const fs=analysis.fitnessWindow?x(analysis.fitnessWindow.startS):null,fe=analysis.fitnessWindow?x(analysis.fitnessWindow.endS):null;
 return <div className="chart-wrap"><div className="chart-legend"><span className="legend-speed">Speed</span><span className="legend-hr">Heart rate</span><span className="legend-segment">Drift segment</span><span className="legend-fitness">Fitness window</span></div><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Speed and heart rate over activity time"><rect className="segment-shade" x={sx} y="8" width={Math.max(1,ex-sx)} height={H-16}/>{fs!==null&&fe!==null&&<rect className="fitness-shade" x={fs} y="8" width={Math.max(1,fe-fs)} height={H-16}/>}<line className="chart-axis" x1={pad} y1={H-pad} x2={W-pad} y2={H-pad}/><path className="speed-line" d={path('speedMph',ySp)}/><path className="hr-line" d={path('hr',yHr)}/><text className="chart-text" x={pad} y={H-10}>0:00</text><text className="chart-text" textAnchor="end" x={W-pad} y={H-10}>{formatDuration(maxT)}</text></svg></div>
}


function WorkoutTimeline({analysis}){
 if(!analysis?.series?.length)return null;
 const total=Math.max(...analysis.series.map(r=>Number.isFinite(r.t)?r.t:0),analysis.analysisEndS||0,1);
 const pct=v=>Math.max(0,Math.min(100,(v/total)*100));
 const preEnd=pct(analysis.startS||0), runStart=pct(analysis.startS||0), runEnd=pct(analysis.endS||total);
 const analysisStart=pct(analysis.analysisStartS||analysis.startS||0), analysisEnd=pct(analysis.analysisEndS||analysis.endS||total);
 const fs=analysis.fitnessWindow?pct(analysis.fitnessWindow.startS):null, fe=analysis.fitnessWindow?pct(analysis.fitnessWindow.endS):null;
 return <div className="viz-card timeline-card"><div className="viz-head"><div><span>WORKOUT TIMELINE</span><strong>Where Endurance Forge is analyzing</strong></div><small>{formatDuration(total)} total</small></div><div className="timeline" role="img" aria-label="Workout timeline showing warm-up, sustained run, analyzed segment, and fitness window"><div className="timeline-base"><div className="timeline-pre" style={{left:0,width:`${preEnd}%`}}/><div className="timeline-run" style={{left:`${runStart}%`,width:`${Math.max(0,runEnd-runStart)}%`}}/><div className="timeline-analysis" style={{left:`${analysisStart}%`,width:`${Math.max(0,analysisEnd-analysisStart)}%`}}/>{fs!==null&&fe!==null&&<div className="timeline-fitness" style={{left:`${fs}%`,width:`${Math.max(0,fe-fs)}%`}}/>}</div><div className="timeline-labels"><span>0:00</span><span>{formatDuration(total)}</span></div></div><div className="viz-legend"><span className="key pre">Warm-up / pre-run</span><span className="key run">Sustained run</span><span className="key analysis">Drift analysis</span><span className="key fitness">Fitness window</span></div></div>
}

function DriftVisual({drift}){
 if(!drift)return null;
 const maxHr=Math.max(drift.firstHr||0,drift.secondHr||0,1), maxSp=Math.max(drift.firstSpeed||0,drift.secondSpeed||0,1);
 const hrw=v=>`${Math.max(3,(v/maxHr)*100)}%`, spw=v=>`${Math.max(3,(v/maxSp)*100)}%`;
 return <div className="viz-card"><div className="viz-head"><div><span>{(drift.label||'HR DRIFT').toUpperCase()}</span><strong>{drift.value>=0?'+':''}{drift.value.toFixed(1)}% workload-normalized</strong></div><small>first half → second half</small></div><div className="drift-pairs"><div className="drift-row"><b>Heart rate</b><div className="paired-bars"><div><i style={{width:hrw(drift.firstHr)}}/><span>{Math.round(drift.firstHr)} bpm</span></div><div><i style={{width:hrw(drift.secondHr)}}/><span>{Math.round(drift.secondHr)} bpm</span></div></div></div><div className="drift-row"><b>Speed</b><div className="paired-bars speed-bars"><div><i style={{width:spw(drift.firstSpeed)}}/><span>{drift.firstSpeed.toFixed(2)} mph</span></div><div><i style={{width:spw(drift.secondSpeed)}}/><span>{drift.secondSpeed.toFixed(2)} mph</span></div></div></div></div><p className="viz-note">Raw HR change {drift.rawHrDrift>=0?'+':''}{drift.rawHrDrift.toFixed(1)}% · speed change {drift.speedChange>=0?'+':''}{drift.speedChange.toFixed(1)}%</p></div>
}

function HrReserveVisual({fit,maxHr,restHr}){
 const mx=Number(maxHr),rest=Number(restHr),avg=fit?.avgHr;
 if(!(mx>rest)&&!Number.isFinite(avg))return null;
 if(!(mx>rest)||!Number.isFinite(avg))return <div className="viz-card reserve-card"><div className="viz-head"><div><span>HEART-RATE RESERVE</span><strong>Profile needed for visualization</strong></div></div><p className="viz-note">Enter known maximum HR and resting HR to place the stable-window response within your HR reserve.</p></div>;
 const p=Math.max(0,Math.min(100,((avg-rest)/(mx-rest))*100));
 return <div className="viz-card reserve-card"><div className="viz-head"><div><span>HEART-RATE RESERVE</span><strong>{Math.round(p)}% HRR in fitness window</strong></div><small>{Math.round(avg)} bpm average</small></div><div className="reserve-track" role="img" aria-label={`Stable-window heart rate is ${Math.round(p)} percent of heart-rate reserve`}><div className="reserve-fill" style={{width:`${p}%`}}/><div className="reserve-marker" style={{left:`${p}%`}}><span>{Math.round(avg)}</span></div></div><div className="reserve-scale"><span>Rest {Math.round(rest)}</span><span>Max {Math.round(mx)}</span></div></div>
}

function CompareBars({runs}){
 if(!runs?.length)return null;
 const usable=runs.filter(r=>Number.isFinite(r.hr)||Number.isFinite(r.drift)); if(!usable.length)return null;
 const maxHr=Math.max(...usable.map(r=>Number.isFinite(r.hr)?r.hr:0),1), maxDrift=Math.max(...usable.map(r=>Number.isFinite(r.drift)?Math.abs(r.drift):0),1);
 return <div className="compare-viz-grid"><div className="viz-card"><div className="viz-head"><div><span>RUN AVG HEART RATE</span><strong>Cardiovascular response by run</strong></div></div><div className="compare-bars">{usable.map((r,i)=><div className="compare-bar-row" key={'hr'+i}><span title={r.name}>{`Run ${i+1}`}</span><div><i className="hr-bar" style={{width:`${Number.isFinite(r.hr)?Math.max(2,r.hr/maxHr*100):0}%`}}/></div><b>{Number.isFinite(r.hr)?Math.round(r.hr)+' bpm':'—'}</b></div>)}</div></div><div className="viz-card"><div className="viz-head"><div><span>HR DRIFT</span><strong>Workload-normalized change by run</strong></div></div><div className="compare-bars">{usable.map((r,i)=><div className="compare-bar-row" key={'drift'+i}><span title={r.name}>{`Run ${i+1}`}</span><div><i className="drift-bar" style={{width:`${Number.isFinite(r.drift)?Math.max(2,Math.abs(r.drift)/maxDrift*100):0}%`}}/></div><b>{Number.isFinite(r.drift)?(r.drift>=0?'+':'')+r.drift.toFixed(1)+'%':'—'}</b></div>)}</div><p className="viz-note">Bar length shows magnitude; the signed value remains the reported result.</p></div></div>
}

function Analyze(){
 const[file,setFile]=useState(null),[activity,setActivity]=useState(null),[error,setError]=useState('');
 const[distance,setDistance]=useState(''),[time,setTime]=useState(''),[grade,setGrade]=useState('0');
 const[maxHr,setMaxHr]=useState(()=>localStorage.getItem('ef-max-hr')||''),[restHr,setRestHr]=useState(()=>localStorage.getItem('ef-rest-hr')||'');
 const[segmentStart,setSegmentStart]=useState(''),[segmentEnd,setSegmentEnd]=useState('');
 const load=async(files)=>{const f=files[0];if(!f)return;setError('');setSegmentStart('');setSegmentEnd('');try{const a=await importActivity(f);setFile(f);setActivity(a);setDistance(Number.isFinite(safeMiles(a))?safeMiles(a).toFixed(3):'');setTime(Number.isFinite(safeTime(a))?formatDuration(safeTime(a)):'')}catch(e){setError(e.message);setActivity(null)}};
 const seconds=useMemo(()=>parseClock(time),[time]), miles=Number(distance), targetM=miles>0?miles*1609.344:NaN;
 const analysis=useMemo(()=>activity?analyzeTreadmillActivity(activity,{targetDistanceM:targetM,targetTimerS:seconds,gradePct:Number(grade)||0,maxHr:Number(maxHr),restHr:Number(restHr),manualStartS:parseClock(segmentStart),manualEndS:parseClock(segmentEnd)}):null,[activity,targetM,seconds,grade,maxHr,restHr,segmentStart,segmentEnd]);
 const pace=miles>0&&seconds>0?pacePerMile(miles,seconds):null,mph=miles>0&&seconds>0?miles/(seconds/3600):null,oxy=mph?oxygenCostLevelRun(mph,Number(grade)||0):null;
 const runMiles=analysis?.avgSpeedMph>0?analysis.avgSpeedMph*(analysis.segmentDurationS/3600):NaN, preMiles=analysis?.preSegmentAvgSpeedMph>0?analysis.preSegmentAvgSpeedMph*(analysis.preSegmentDurationS/3600):NaN;
 const fit=analysis?.fitness, drift=analysis?.drift;
 const saveProfile=(setter,key)=>(e)=>{setter(e.target.value);localStorage.setItem(key,e.target.value)};
 const download=()=>{try{const out=correctActivityFile(activity,targetM,seconds);const blob=new Blob([out.bytes],{type:'application/octet-stream'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name.replace(/\.fit$/i,'')+'_EnduranceForge_Corrected.fit';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){setError(e.message)}};
 return <section className="workspace"><div className="page-title"><div><div className="eyebrow">SINGLE ACTIVITY ANALYSIS</div><h1>Treadmill Run Analyzer</h1><p>Endurance Forge identifies the sustained running portion before calculating drift or aerobic-fitness estimates. You can override the detected segment at any time.</p></div><div className="pill">PROCESSED LOCALLY IN YOUR BROWSER</div></div>
 {!activity?<DropZone onFiles={load}/>:<><div className="filebar"><div><b>{file.name}</b><span><em className={'format-tag '+activity.format.toLowerCase()}>{activity.format}</em>{activity.records.length} samples · {activity.laps.length} laps</span></div><button className="link" onClick={()=>{setActivity(null);setFile(null);setError('')}}>Choose another file</button></div>
 <div className="two-col"><div className="panel"><div className="panel-head"><div><span>01</span><h2>Treadmill truth</h2></div><small>Authoritative workload inputs</small></div><div className="form-grid"><label>Distance (miles)<input value={distance} onChange={e=>setDistance(e.target.value)} inputMode="decimal"/></label><label>Time<input value={time} onChange={e=>setTime(e.target.value)}/></label><label>Incline / grade (%)<input value={grade} onChange={e=>setGrade(e.target.value)} inputMode="decimal"/></label></div><p className="note">These values calibrate the workload trace. Grade defaults to 0% and is never inferred from the watch.</p></div>
 <div className="panel"><div className="panel-head"><div><span>02</span><h2>Recorded activity</h2></div><small>{activity.sourceLabel}</small></div><div className="mini-grid"><Metric label="Recorded distance" value={Number.isFinite(safeMiles(activity))?safeMiles(activity).toFixed(2)+' mi':'—'}/><Metric label="Recorded time" value={Number.isFinite(safeTime(activity))?formatDuration(safeTime(activity)):'—'}/><Metric label="Average HR" value={Number.isFinite(activity.avgHr)?Math.round(activity.avgHr)+' bpm':'—'}/><Metric label="Activity max HR" value={Number.isFinite(activity.maxHr)?Math.round(activity.maxHr)+' bpm':'—'} sub="not assumed to be HRmax"/></div></div></div>
 <div className="panel capability-panel"><div className="panel-head"><div><span>03</span><h2>Detected data capabilities</h2></div><small>Metrics adapt to the file</small></div><Capabilities activity={activity}/></div>
 <div className="panel segment-panel"><div className="panel-head"><div><span>04</span><h2>Workout structure</h2></div><small>{analysis?.auto?.detected?'Sustained running detected':'Automatic segmentation limited'}</small></div>
 {analysis&&<><div className="structure-grid"><Metric label="Pre-run / warm-up" value={analysis.preSegmentDurationS>30?formatDuration(analysis.preSegmentDurationS):'None detected'} sub={Number.isFinite(preMiles)?`≈ ${preMiles.toFixed(2)} mi from speed trace`:''}/><Metric label="Detected run" value={formatDuration(analysis.segmentDurationS)} sub={Number.isFinite(runMiles)?`≈ ${runMiles.toFixed(2)} mi · ${fmtMph(analysis.avgSpeedMph)}`:fmtMph(analysis.avgSpeedMph)}/><Metric label="Analysis starts" value={formatDuration(analysis.analysisStartS)} sub={analysis.analysisStartS>analysis.startS?'HR-settling transition trimmed':'No automatic trim'}/><Metric label="Run avg HR" value={Number.isFinite(analysis.avgHr)?Math.round(analysis.avgHr)+' bpm':'—'} sub={analysis.fitnessWindow?`Fitness window ${formatDuration(analysis.fitnessWindow.startS)}–${formatDuration(analysis.fitnessWindow.endS)}`:''}/></div><ActivityChart analysis={analysis}/><WorkoutTimeline analysis={analysis}/><div className="segment-controls"><div><strong>Override analyzed segment</strong><span>Leave blank to use automatic detection.</span></div><label>Start<input value={segmentStart} onChange={e=>setSegmentStart(e.target.value)} placeholder={formatDuration(analysis.analysisStartS)}/></label><label>End<input value={segmentEnd} onChange={e=>setSegmentEnd(e.target.value)} placeholder={formatDuration(analysis.analysisEndS)}/></label><button className="secondary compact" onClick={()=>{setSegmentStart('');setSegmentEnd('')}}>Use automatic</button></div></>}
 </div>
 <div className="panel profile-panel"><div className="panel-head"><div><span>05</span><h2>Physiological inputs</h2></div><small>Stored only in this browser</small></div><div className="profile-row"><label>Known maximum HR (bpm)<input value={maxHr} onChange={saveProfile(setMaxHr,'ef-max-hr')} inputMode="numeric" placeholder="e.g. 185"/></label><label>Resting HR (bpm)<input value={restHr} onChange={saveProfile(setRestHr,'ef-rest-hr')} inputMode="numeric" placeholder="e.g. 55"/></label><p>These are optional for general analysis but required for the current submaximal EF Aerobic Fitness Estimate. The highest HR in this workout is <b>not</b> substituted for known HRmax.</p></div></div>
 <div className="metric-grid five"><Metric label="Corrected pace" value={pace||'—'} sub="whole activity"/><Metric label="Corrected speed" value={mph?mph.toFixed(2)+' mph':'—'} sub="whole activity"/><Metric label="Running O₂ cost" value={fit?.workloadVo2?fit.workloadVo2.toFixed(1):(analysis?.avgSpeedMph?oxygenCostLevelRun(analysis.avgSpeedMph,Number(grade)||0).toFixed(1):oxy?.toFixed(1)||'—')} sub="mL/kg/min · workload"/><Metric label={drift?.label||'HR drift'} value={drift?(drift.value>=0?'+':'')+drift.value.toFixed(1)+'%':'—'} sub={drift?'running segment · workload-normalized':'needs comparable HR + speed'}/><Metric label="EF Aerobic Fitness Estimate" value={fit&&Number.isFinite(fit.value)?fit.value.toFixed(1):'—'} sub={fit&&Number.isFinite(fit.value)?`mL/kg/min · VO₂max-equivalent · ${fit.confidence} inference`:(fit?.reason||'requires suitable segment + HR profile')} tone={confidenceClass(fit?.confidence)}/></div>
 <div className="metric-help"><span><b>Running O₂ Cost</b> describes the oxygen demand of the treadmill workload. <b>EF Aerobic Fitness Estimate</b> is the VO₂max-equivalent capacity inferred from workload + heart-rate response. See Metrics Guide for interpretation and Methodology for calculations.</span></div>
 <div className="insight-viz-grid"><DriftVisual drift={drift}/><HrReserveVisual fit={fit} maxHr={maxHr} restHr={restHr}/></div>
 <div className="result-panel"><div><div className="eyebrow">ENDURANCE FORGE AEROBIC ANALYSIS</div><h2>{fit&&Number.isFinite(fit.value)?`EF Aerobic Fitness Estimate: ${fit.value.toFixed(1)} mL/kg/min`:'Insufficient data for a reliable aerobic fitness estimate.'}</h2><div className="equivalent-label">TREADMILL-DERIVED VO₂MAX-EQUIVALENT ESTIMATE</div><p>{fit?.reason||'The current activity does not support the estimate yet.'} {drift?`The drift calculation compares workload-normalized HR within the selected running segment; average speed changed ${drift.speedChange>=0?'+':''}${drift.speedChange.toFixed(1)}% between halves.`:''}</p><div className="disclaimer">Comparable to VO₂max in concept and units, but not directly interchangeable with a laboratory or device-manufacturer value. It is not Garmin VO₂max and not a laboratory VO₂max measurement.</div></div><div className={'status-card '+confidenceClass(fit?.confidence)}><span>Inference confidence</span><strong>{fit?.confidence||'Unavailable'}</strong><small>{fit&&Number.isFinite(fit.hrr)?`${Math.round(fit.hrr*100)}% HR reserve · ${formatDuration(fit.durationS)} stable window`:fit?.reason}</small><span className="quality-line">Data quality: <b>{analysis?.dataQuality?.level||'Unavailable'}</b></span></div></div>
 <div className="actions"><button className="primary" disabled={activity.format!=='FIT'||!miles||!seconds} onClick={download}>{activity.format==='FIT'?'Download corrected FIT':`Corrected ${activity.format} export — later`}</button><span>Your original file is never modified.</span></div></>}{error&&<div className="error">{error}</div>}</section>
}

function MultiRunPlot({combined}){
 if(!combined?.available||!combined.points?.length)return null;
 const pts=combined.points, W=760,H=310,padL=58,padR=22,padT=25,padB=44;
 const xs=pts.map(p=>p.hrr*100),ys=pts.map(p=>p.workloadVo2);
 const minX=Math.max(30,Math.floor((Math.min(...xs)-5)/5)*5),maxX=Math.min(95,Math.ceil((Math.max(...xs)+5)/5)*5);
 const lineY=xPct=>3.5+(combined.value-3.5)*(xPct/100);
 const lineYs=[lineY(minX),lineY(maxX)],minY=Math.max(10,Math.floor((Math.min(...ys,...lineYs)-2)/5)*5),maxY=Math.ceil((Math.max(...ys,...lineYs)+2)/5)*5;
 const x=v=>padL+((v-minX)/Math.max(1,maxX-minX))*(W-padL-padR),y=v=>H-padB-((v-minY)/Math.max(1,maxY-minY))*(H-padT-padB);
 return <div className="viz-card multi-plot"><div className="viz-head"><div><span>WORKLOAD–HEART-RATE RELATIONSHIP</span><strong>Qualifying runs vs combined EF model</strong></div><small>{combined.eligibleCount} runs · {combined.distinctWorkloads} workload levels</small></div><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Workload oxygen cost versus heart-rate reserve for qualifying treadmill runs"><line className="chart-axis" x1={padL} y1={H-padB} x2={W-padR} y2={H-padB}/><line className="chart-axis" x1={padL} y1={padT} x2={padL} y2={H-padB}/><line className="model-line" x1={x(minX)} y1={y(lineY(minX))} x2={x(maxX)} y2={y(lineY(maxX))}/>{pts.map((p,i)=><g key={i}><circle className="run-point" cx={x(p.hrr*100)} cy={y(p.workloadVo2)} r="6"/><text className="chart-text point-label" x={x(p.hrr*100)+8} y={y(p.workloadVo2)-8}>{`Run ${p.runIndex+1}`}</text></g>)}<text className="chart-text" x={(padL+W-padR)/2} y={H-9} textAnchor="middle">Heart-rate reserve (%)</text><text className="chart-text axis-label-y" transform={`translate(15 ${(padT+H-padB)/2}) rotate(-90)`} textAnchor="middle">Workload O₂ (mL/kg/min)</text><text className="model-label" x={W-padR} y={Math.max(padT+12,y(lineY(maxX))-8)} textAnchor="end">EF {combined.value.toFixed(1)}</text></svg><p className="viz-note">Points are stable-window observations. The line is the robust combined relationship; it is not a laboratory VO₂ measurement.</p></div>
}

function Compare(){
 const[runs,setRuns]=useState([]),[error,setError]=useState('');
 const[maxHr,setMaxHr]=useState(()=>localStorage.getItem('ef-max-hr')||''),[restHr,setRestHr]=useState(()=>localStorage.getItem('ef-rest-hr')||'');
 const saveProfile=(setter,key)=>(e)=>{setter(e.target.value);localStorage.setItem(key,e.target.value)};
 const load=async(files)=>{setError('');const out=[];for(const f of files){try{const a=await importActivity(f),m=safeMiles(a),t=safeTime(a);out.push({id:`${f.name}-${f.size}-${f.lastModified}`,name:f.name,format:a.format,activity:a,distance:Number.isFinite(m)?m.toFixed(3):'',time:Number.isFinite(t)?formatDuration(t):'',grade:'0',included:true})}catch(e){setError(prev=>prev+(prev?'\n':'')+f.name+': '+e.message)}}setRuns(out)};
 const patchRun=(id,field,value)=>setRuns(rs=>rs.map(r=>r.id===id?{...r,[field]:value}:r));
 const analyzed=useMemo(()=>runs.map((r,runIndex)=>{const miles=Number(r.distance),seconds=parseClock(r.time),gradePct=Number(r.grade)||0,targetM=miles>0?miles*1609.344:NaN;const an=analyzeTreadmillActivity(r.activity,{targetDistanceM:targetM,targetTimerS:seconds,gradePct,maxHr:Number(maxHr),restHr:Number(restHr)}),fit=an?.fitness;return {...r,runIndex,miles,seconds,pace:miles>0&&seconds>0?pacePerMile(miles,seconds):'—',hr:an?.avgHr,drift:an?.drift?.value,segment:an?.segmentDurationS,fitValue:fit?.value,hrr:fit?.hrr,workloadVo2:fit?.workloadVo2,singleConfidence:fit?.confidence,dataQuality:an?.dataQuality?.level,analysis:an}}),[runs,maxHr,restHr]);
 const combined=useMemo(()=>combineAerobicFitness(analyzed),[analyzed]);
 return <section className="workspace"><div className="page-title"><div><div className="eyebrow">MULTI-RUN AEROBIC ANALYSIS</div><h1>Compare treadmill runs</h1><p>Analyze several treadmill activities with a shared physiological profile. Each run is evaluated independently first; qualifying stable-window observations are then combined into a robust EF Aerobic Fitness Estimate.</p></div><div className="pill">MULTI-RUN MODEL</div></div>
 <DropZone multiple onFiles={load} title="Drop several FIT, TCX, or GPX files here"/>
 {runs.length>0&&<><div className="panel profile-panel"><div className="panel-head"><div><span>01</span><h2>Shared physiological profile</h2></div><small>Used for every selected run</small></div><div className="profile-row"><label>Known maximum HR<input value={maxHr} onChange={saveProfile(setMaxHr,'ef-max-hr')} inputMode="numeric" placeholder="e.g. 179"/></label><label>Resting HR<input value={restHr} onChange={saveProfile(setRestHr,'ef-rest-hr')} inputMode="numeric" placeholder="e.g. 47"/></label><p>Use the same known maximum and resting HR across the comparison. The maximum HR observed in an uploaded workout is not substituted for physiological HRmax.</p></div></div>
 <div className="panel table-panel multi-input-panel"><div className="panel-head"><div><span>02</span><h2>Treadmill truth by run</h2></div><small>Correct workload inputs before combining</small></div><p className="note">Recorded indoor distance is used as the starting value. Replace it with treadmill distance/time when they differ, and enter grade for each run. Uncheck any run you do not want included in the combined model.</p><div className="table-wrap"><table className="multi-input-table"><thead><tr><th>Use</th><th>File</th><th>Distance mi</th><th>Time</th><th>Grade %</th><th>Stable HR</th><th>HRR</th><th>O₂ workload</th><th>Single-run EF</th><th>Quality</th></tr></thead><tbody>{analyzed.map(r=><tr key={r.id}><td><input type="checkbox" checked={r.included} onChange={e=>patchRun(r.id,'included',e.target.checked)} aria-label={`Include ${r.name}`}/></td><td><b>{r.name}</b><br/><em className={'format-tag '+r.format.toLowerCase()}>{r.format}</em></td><td><input className="table-input" value={r.distance} onChange={e=>patchRun(r.id,'distance',e.target.value)} inputMode="decimal"/></td><td><input className="table-input time-input" value={r.time} onChange={e=>patchRun(r.id,'time',e.target.value)}/></td><td><input className="table-input grade-input" value={r.grade} onChange={e=>patchRun(r.id,'grade',e.target.value)} inputMode="decimal"/></td><td>{Number.isFinite(r.analysis?.fitness?.avgHr)?Math.round(r.analysis.fitness.avgHr)+' bpm':'—'}</td><td>{Number.isFinite(r.hrr)?Math.round(r.hrr*100)+'%':'—'}</td><td>{Number.isFinite(r.workloadVo2)?r.workloadVo2.toFixed(1):'—'}</td><td>{Number.isFinite(r.fitValue)?r.fitValue.toFixed(1):'—'}<small className="cell-sub">{r.singleConfidence||''}</small></td><td>{r.dataQuality||'—'}</td></tr>)}</tbody></table></div></div>
 <div className={'multi-result '+confidenceClass(combined.confidence)}><div><div className="eyebrow">COMBINED EF AEROBIC FITNESS ESTIMATE</div><h2>{combined.available?`${combined.value.toFixed(1)} mL/kg/min`:'Not enough qualifying runs yet'}</h2><div className="equivalent-label">ROBUST MULTI-RUN · TREADMILL-DERIVED VO₂MAX-EQUIVALENT</div><p>{combined.reason}</p></div><div className="multi-result-stats"><Metric label="Inference confidence" value={combined.confidence}/><Metric label="Qualifying runs" value={`${combined.eligibleCount||0} / ${runs.length}`}/><Metric label="Workload span" value={combined.available?combined.workloadRange.toFixed(1):'—'} sub="mL/kg/min"/><Metric label="Run agreement" value={combined.available?`MAD ${combined.spreadMad.toFixed(1)}`:'—'} sub="single-run EF spread"/></div></div>
 {combined.available&&<MultiRunPlot combined={combined}/>}<CompareBars runs={analyzed.filter(r=>r.included)}/>
 <div className="panel table-panel"><div className="panel-head"><div><span>03</span><h2>Run-by-run results</h2></div><small>Independent analysis retained</small></div><div className="table-wrap"><table><thead><tr><th>Run</th><th>Pace</th><th>Run segment</th><th>Run avg HR</th><th>HR drift</th><th>EF estimate</th><th>Inference</th></tr></thead><tbody>{analyzed.map((r,i)=><tr key={r.id}><td>Run {i+1}</td><td>{r.pace}</td><td>{Number.isFinite(r.segment)?formatDuration(r.segment):'—'}</td><td>{Number.isFinite(r.hr)?Math.round(r.hr)+' bpm':'—'}</td><td>{Number.isFinite(r.drift)?(r.drift>=0?'+':'')+r.drift.toFixed(1)+'%':'—'}</td><td>{Number.isFinite(r.fitValue)?r.fitValue.toFixed(1):'—'}</td><td>{r.singleConfidence||'Unavailable'}</td></tr>)}</tbody></table></div></div>
 <div className="disclaimer multi-disclaimer">The combined estimate does not average runs blindly. It fits the workload-above-resting-demand relationship to HR reserve across qualifying runs, uses data-quality/drift weighting and robust residual weighting, and evaluates run-to-run agreement and workload diversity before assigning confidence.</div></>}{error&&<pre className="error">{error}</pre>}</section>
}

function MetricsGuide(){return <section className="workspace methodology" id="ef-guide"><div className="page-title"><div><div className="eyebrow">METRICS GUIDE</div><h1>What your results are telling you</h1><p>A plain-language guide to the metrics reported by Endurance Forge. For equations, assumptions, and algorithm details, see Methodology.</p></div><div className="pill">PUBLIC BETA</div></div>
<div className="compare-callout"><h2>Is EF Aerobic Fitness Estimate VO₂max?</h2><p><b>It is a treadmill-derived VO₂max-equivalent estimate.</b> Endurance Forge estimates the aerobic capacity consistent with treadmill workload and cardiovascular response. It uses the conventional VO₂max units of mL/kg/min, but oxygen consumption is not directly measured. Treat it as an analytical estimate for tracking and comparison, not as a laboratory measurement or a device-manufacturer value.</p></div>
<div className="panel prose"><h2>VO₂max comparison</h2><div className="table-wrap"><table><thead><tr><th>Metric</th><th>What it represents</th><th>How it is obtained</th></tr></thead><tbody>
<tr><td><b>Laboratory VO₂max</b></td><td>Maximum measured aerobic capacity</td><td>Direct respiratory-gas measurement during a maximal exercise test.</td></tr>
<tr><td><b>Device VO₂max</b></td><td>Estimated VO₂max</td><td>A device manufacturer's proprietary model using exercise and physiological data.</td></tr>
<tr><td><b>EF Aerobic Fitness Estimate</b></td><td>Treadmill-derived VO₂max-equivalent aerobic capacity</td><td>Endurance Forge inference from treadmill workload, heart-rate response, workout structure, and a qualifying stable analysis window.</td></tr>
<tr><td><b>Running O₂ Cost</b></td><td>Oxygen demand of the current treadmill workload</td><td>Calculated from running speed and treadmill grade. This is workload, not VO₂max.</td></tr>
</tbody></table></div>
<h2>EF Aerobic Fitness Estimate</h2><p><b>What it tells you:</b> the aerobic capacity that is consistent with your treadmill workload and cardiovascular response. Higher values generally indicate greater estimated aerobic capacity. The most useful interpretation is repeatability and trend across suitable workouts, not treating one result as an exact physiological measurement.</p><p><b>Why confidence matters:</b> a single submaximal run requires extrapolation. Endurance Forge therefore caps single-run inference confidence at Moderate even when the underlying data quality is High. Multi-run modeling can increase confidence when qualifying runs at meaningfully different workloads agree.</p>
<h2>Multi-run EF Aerobic Fitness Estimate</h2><p><b>What it tells you:</b> whether several qualifying treadmill runs support one consistent aerobic-capacity estimate. Endurance Forge analyzes each run independently, then combines stable-window workload and HR-reserve observations with a robust model. Runs with weaker data quality, substantial drift, or poor agreement receive less influence. High inference confidence requires corroboration across multiple suitable runs and meaningful workload diversity; it does not mean laboratory validation.</p>
<h2>Running O₂ Cost</h2><p><b>What it tells you:</b> the estimated metabolic demand of the running workload in mL/kg/min. It answers “how much oxygen would this workload typically require?” rather than “what is my maximum aerobic capacity?” Grade substantially affects workload, so enter treadmill incline when known.</p>
<h2>HR Drift / Aerobic Decoupling</h2><p><b>What it tells you:</b> whether heart rate rises relative to workload during a sustained running segment. Positive drift means cardiovascular response increased as the run progressed. Lower drift during genuinely comparable workouts can be consistent with better aerobic durability, but temperature, hydration, fatigue, caffeine, illness, stress, and sensor behavior can also affect it.</p>
<h2>HR Reserve</h2><p>Heart-rate reserve places exercise HR between resting HR and known maximum HR. Endurance Forge uses it in the current submaximal fitness model. The highest HR observed in one workout is not automatically treated as your true maximum HR.</p>
<h2>Stable Fitness Window</h2><p>The fitness estimate does not blindly average the entire activity. Endurance Forge first identifies sustained running, trims the walk-to-run HR transition when appropriate, and then searches for a stable workload/HR window. Cardiac drift continues to use the longer comparable running segment.</p>
<h2>Data Quality vs Inference Confidence</h2><p><b>Data Quality</b> describes how suitable and stable the measured data are. <b>Inference Confidence</b> describes how strongly that activity supports the physiological conclusion. High-quality data can still produce only Moderate inference confidence because estimating maximal aerobic capacity from one submaximal run involves uncertainty.</p>
<h2>Corrected Pace and Speed</h2><p>When you enter treadmill truth, Endurance Forge uses the treadmill distance and time as the authoritative workload values. This is especially useful when watch-estimated indoor distance differs from the treadmill.</p>
<h2>Workout Segmentation</h2><p>Walking, warm-up, sustained running, recovery, and cooldown can have very different cardiovascular responses. Endurance Forge attempts to isolate sustained running before calculating physiological metrics. The automatic selection can be manually overridden for unusual workouts.</p>
</div></section>}

function Methodology(){return <section className="workspace methodology"><div className="page-title"><div><div className="eyebrow">ANALYSIS METHODOLOGY</div><h1>Analysis methodology</h1><p>Endurance Forge separates source-file parsing, treadmill calibration, workout segmentation, workload calculation, physiological inference, and confidence assessment. This page explains how those steps work so the reported metrics can be understood and evaluated.</p></div><div className="pill">TRANSPARENT METHODOLOGY</div></div>
<div className="method-grid"><article><b>01 · Normalize</b><h3>FIT, TCX, GPX</h3><p>Each source format becomes the same timestamped Endurance Forge activity model.</p></article><article><b>02 · Segment</b><h3>Find sustained running</h3><p>A smoothed speed trace identifies a sustained running block and separates slower walking/warm-up when the signal supports it.</p></article><article><b>03 · Infer</b><h3>Use comparable data</h3><p>Drift uses the longer comparable run; aerobic-fitness inference uses a stable workload/HR window inside it.</p></article></div>
<div className="panel prose"><h2>Analysis pipeline</h2><p><b>Raw activity → treadmill truth calibration → sustained-run detection → HR settling trim → stable-window selection → workload O₂ calculation → HR-reserve calculation → single-run EF inference → optional multi-run robust combination → confidence assessment.</b></p>
<h2>Running O₂ Cost</h2><p>For level/graded treadmill running, Endurance Forge currently uses the ACSM-style running metabolic relationship:</p><div className="formula">VO₂ workload = 0.2v + 0.9vG + 3.5</div><p>where <b>v</b> is speed in meters per minute and <b>G</b> is fractional treadmill grade (for example, 1% = 0.01). The result is expressed in mL/kg/min. This describes estimated oxygen demand of the workload; it is <b>not</b> VO₂max.</p>
<h2>Heart-rate reserve</h2><div className="formula">HRR fraction = (exercise HR − resting HR) / (maximum HR − resting HR)</div><p>The submaximal model requires user-supplied known maximum HR and resting HR. Activity maximum HR is deliberately not substituted for physiological HRmax.</p>
<h2>EF Aerobic Fitness Estimate</h2><p>The EF Aerobic Fitness Estimate is intended to represent a <b>treadmill-derived VO₂max-equivalent aerobic capacity</b>. The Endurance Forge model relates the stable-window workload above resting metabolic demand to the fraction of heart-rate reserve used:</p><div className="formula">EF estimate = 3.5 + (workload VO₂ − 3.5) / HRR fraction</div><p>This assumes a useful approximately linear submaximal relationship between oxygen reserve and heart-rate reserve. Because that assumption is an approximation and the calculation extrapolates beyond the observed submaximal workload, the result is not directly interchangeable with laboratory VO₂max or any manufacturer's proprietary estimate.</p>
<h2>Multi-run EF model</h2><p>When two or more qualifying activities are selected in Compare Runs, Endurance Forge retains every single-run result and then models all usable stable-window observations together. Define <b>xᵢ</b> as HR-reserve fraction and <b>yᵢ</b> as workload oxygen demand above resting demand:</p><div className="formula">xᵢ = HRRᵢ &nbsp;&nbsp; · &nbsp;&nbsp; yᵢ = workload VO₂ᵢ − 3.5</div><p>The combined model estimates one aerobic-reserve slope <b>β</b> through the physiological resting anchor:</p><div className="formula">β = Σ(wᵢ xᵢ yᵢ) / Σ(wᵢ xᵢ²) &nbsp;&nbsp; and &nbsp;&nbsp; Combined EF = 3.5 + β</div><p>Initial run weights reflect stable-window data quality, single-run inference quality, and the magnitude of aerobic drift. Endurance Forge then applies iterative robust residual weighting so one discordant run has less ability to pull the result away from the relationship supported by the other runs. This is intentionally different from simply averaging the individual EF estimates.</p><h2>Multi-run eligibility and confidence</h2><p>A run must have a valid stable-window EF estimate, usable workload oxygen cost, and HR reserve within the accepted submaximal range to enter the combined model. The user can exclude individual activities. <b>High</b> multi-run inference confidence currently requires at least three qualifying runs, at least three High/Moderate-quality observations, meaningful workload and HRR span, at least two distinct workload levels, and tight run-to-run agreement. <b>Moderate</b> confidence requires at least two suitable corroborating runs with acceptable agreement and some workload separation. Otherwise the combined result remains Low or unavailable.</p><p>Confidence describes internal corroboration of the Endurance Forge model. It does not establish laboratory accuracy. Repeated nearly identical workloads provide less independent information than suitable runs spanning different submaximal workloads, and environmental or physiological factors can shift HR independently of aerobic capacity.</p>
<h2>Stable estimation window</h2><p>After the sustained run and HR-settling transition are identified, Endurance Forge searches candidate windows for consistent treadmill speed and a steadier HR/workload relationship. Longer runs generally allow a 15-minute candidate window; shorter qualifying runs use shorter windows. Candidate scoring penalizes workload variability, HR drift/slope, and late-window placement. The selected window is highlighted on the activity chart.</p>
<h2>HR drift / aerobic decoupling</h2><p>The longer comparable running segment is divided into two portions. Endurance Forge compares heart rate relative to speed so modest workload changes are less likely to masquerade as physiological drift:</p><div className="formula">Drift % = [(HR₂ / speed₂) / (HR₁ / speed₁) − 1] × 100</div><p>If average speed changes materially between halves, the result is labeled aerobic decoupling rather than simple steady-state HR drift.</p>
<h2>Data quality vs inference confidence</h2><p>Data Quality considers usable duration, sampling, and workload stability in the selected fitness window. Inference Confidence considers whether the physiological extrapolation itself is well supported. A single-activity submaximal estimate is intentionally capped at <b>Moderate</b> inference confidence. Significant drift, workload instability, an unsuitable HR-reserve range, or weak data can reduce it to Low or make the estimate unavailable.</p>
<h2>What Endurance Forge does not claim</h2><p>Endurance Forge does not directly measure oxygen consumption, diagnose fitness or health conditions, reproduce Garmin or another manufacturer's proprietary VO₂max algorithm, or claim laboratory accuracy. Results should be interpreted as analytical estimates rather than direct physiological measurements.</p>
<h2>Privacy and local processing</h2><p>Activity-file parsing and analysis occur in the browser. Raw FIT, TCX, and GPX activity files are not uploaded to an Endurance Forge server by this application. Maximum-HR and resting-HR profile values are stored locally in browser storage.</p>
<h2>Public beta and feedback</h2><p>Endurance Forge is currently in beta while its analytical methods are evaluated across a wider range of runners, workout structures, devices, and treadmill workloads. If a result appears incorrect or unexpected, please report it so the analysis can be reviewed and improved.</p><p><a className="doc-link" href="https://github.com/StatForge-dev/endurance-forge-web/issues" target="_blank" rel="noreferrer">Report feedback or an issue on GitHub ↗</a></p>
<div className="support-card"><div><span className="support-kicker">SUPPORT THE PROJECT</span><h2>Support Endurance Forge</h2><p>Endurance Forge is independently developed and free to use. If you find it useful, you can help support continued development.</p></div><a className="coffee-button" href="https://buymeacoffee.com/enduranceforge" target="_blank" rel="noreferrer">☕ Buy the developer a coffee</a></div>
</div></section>}

function App(){
 const[page,setPage]=useState(pageFromLocation);
 const go=(next)=>{const path=pagePaths[next]||'/';if(window.location.pathname!==path)window.history.pushState({page:next},'',path);setPage(next);window.scrollTo({top:0,behavior:'auto'})};
 useEffect(()=>{const onPop=()=>setPage(pageFromLocation());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
 useEffect(()=>{const meta=pageMeta[page]||pageMeta.home;document.title=meta.title;let d=document.querySelector('meta[name="description"]');if(d)d.setAttribute('content',meta.description);let c=document.querySelector('link[rel="canonical"]');if(c)c.setAttribute('href','https://endurance-forge.com'+(pagePaths[page]||'/'));let og=document.querySelector('meta[property="og:url"]');if(og)og.setAttribute('content','https://endurance-forge.com'+(pagePaths[page]||'/'));},[page]);
 const body=page==='home'?<Home go={go}/>:page==='analyze'?<Analyze/>:page==='compare'?<Compare/>:page==='guide'?<MetricsGuide/>:<Methodology/>;
 return <Shell page={page} go={go}>{body}</Shell>
}
createRoot(document.getElementById('root')).render(<App/>);
